#!/bin/bash -e

# Author: Daniel Niasoff <dniasoff@gmail.com>
# based on work by Carl Kittelberger <icedream@icedream.pw>

step="vault-ssh-selinux-fix"
printf "Starting to run ${step}\n"

. /etc/sysconfig/heat-params

ssh_cmd="ssh -F /srv/magnum/.ssh/config root@localhost"

vault_ssh_enabled=$(echo $VAULT_SSH_ENABLED | tr '[:upper:]' '[:lower:]')
vault_url=$(echo $VAULT_URL | tr '[:upper:]' '[:lower:]')


if [[ "${vault_ssh_enabled}" = "true" && -n "${vault_url}" ]]; then


# Just used to get a guaranteed empty Docker context dir
empty_dir="$(mktemp -d)"

dockerfile="$(mktemp)"

cleanup() {
  if [ -d "$empty_dir" ]
  then
    rm -rf "$empty_dir"
  fi
  if [ -f "$dockerfile" ]
  then
    rm -f "$dockerfile"
  fi
}
trap cleanup EXIT

echo j/98+QEAAAABAAAAEAAAAI3/fPkPAAAAU0UgTGludXggTW9kdWxlAgAAABQAAAABAAAACAAAAAAAAAAJAAAAdmF1bHQtb3RwAwAAADEuMEAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAKAAAAAAAAAAMAAAABAAAAAQAAAAAAAAB0Y3Bfc29ja2V0DAAAAAEAAABuYW1lX2Nvbm5lY3QDAAAAAAAAAAIAAAABAAAAAQAAAAAAAABkaXIEAAAAAQAAAHJlYWQIAAAAAAAAAAQAAAACAAAAAgAAAAAAAABsbmtfZmlsZQcAAAACAAAAZ2V0YXR0cgQAAAABAAAAcmVhZAQAAAAAAAAAAQAAAAMAAAADAAAAAAAAAGZpbGUGAAAAAgAAAGNyZWF0ZQQAAAADAAAAcmVhZAQAAAABAAAAb3BlbgEAAAABAAAACAAAAAEAAAAAAAAAb2JqZWN0X3JAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAQAAAAEAAAACwAAAAMAAAABAAAAAQAAAAAAAABAAAAAAAAAAAAAAABodHRwX3BvcnRfdAkAAAABAAAAAQAAAAEAAAAAAAAAQAAAAAAAAAAAAAAAdmFyX2xvZ190EAAAAAQAAAABAAAAAQAAAAAAAABAAAAAAAAAAAAAAABjb250YWluZXJfZmlsZV90BgAAAAIAAAABAAAAAQAAAAAAAABAAAAAAAAAAAAAAABzc2hkX3QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAAAAAAAAAAACAAAAAEAAAAAAAAAQAAAAEAAAAABAAAAAAAAAAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAAQAAAAAAAAABAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAEAAAABAAAAAAAAAEAAAABAAAAAAQAAAAAAAAACAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAAEAAAAAAAAAAQAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAACAAAAAQAAAAAAAABAAAAAQAAAAAEAAAAAAAAAAgAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAABAAAAAAAAAAQAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAEAAAADAAAAAQAAAAEAAAAAAAAAQAAAAEAAAAABAAAAAAAAAAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAAQAAAAAAAAAIAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAABAAAAAgAAAAEAAAABAAAAAAAAAEAAAABAAAAAAQAAAAAAAAACAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAAEAAAAAAAAACAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAEAAAAAQAAAAAAAABAAAAAQAAAAAEAAAAAAAAAAgAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAABAAAAAAAAAAgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAEAAAAEAAAAAQAAAAEAAAAAAAAAQAAAAEAAAAABAAAAAAAAAAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAAQAAAAAAAAAIAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAEAAAABAAAAAAAAAEAAAABAAAAAAQAAAAAAAAACAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAAEAAAAAAAAACAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAQAAAAQAAAACAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAABAAAAAAQAAAAAAAAAPAAAAAAAAAEAAAAAAAAAAAAAAAEAAAABAAAAAAQAAAAAAAAAPAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAQAAABAAAAAQAAAAAEAAAAAAAAABwAAAAAAAABAAAAAQAAAAAEAAAAAAAAAAQAAAAAAAABAAAAAQAAAAAEAAAAAAAAAAQAAAAAAAABAAAAAQAAAAAEAAAAAAAAAAwAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAACgAAAHRjcF9zb2NrZXQBAAAAAQAAAAEAAAADAAAAZGlyAQAAAAEAAAABAAAACAAAAGxua19maWxlAQAAAAEAAAABAAAABAAAAGZpbGUBAAAAAQAAAAEAAAABAAAACAAAAG9iamVjdF9yAgAAAAEAAAABAAAABAAAAAsAAABodHRwX3BvcnRfdAEAAAABAAAAAQAAAAkAAAB2YXJfbG9nX3QBAAAAAQAAAAEAAAAQAAAAY29udGFpbmVyX2ZpbGVfdAEAAAABAAAAAQAAAAYAAABzc2hkX3QBAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA== | base64 -d > $empty_dir/vault-otp.pp


# NOTE - not sure if policycoreutils-devel is necessary here, didn't test it with it removed
cat >"$dockerfile" <<DEOF
FROM fedora
RUN yum install -y policycoreutils-python-utils policycoreutils-devel && yum clean all
COPY vault-otp.pp /root/vault-otp.pp
DEOF

image_name="$($ssh_cmd podman build -f "$dockerfile" "$empty_dir" | tail -n1)"

secontainer() {
  $ssh_cmd podman run --privileged --rm \
    -v /var/run:/var/run \
    -v /etc/selinux:/etc/selinux \
    -v /proc:/proc \
    -v /sys:/sys \
    "$image_name" "$@"
}

secontainer semodule -i /root/vault-otp.pp

# workaround from https://github.com/coreos/fedora-coreos-tracker/issues/701 to keep selinux policy files in base config state
$ssh_cmd rsync -rcl /usr/etc/selinux/ /etc/selinux/

fi
