#!/bin/bash -e

# Author: Daniel Niasoff <dniasoff@gmail.com>
# based on work by Carl Kittelberger <icedream@icedream.pw>

step="vault-ssh-selinux-fix"
printf "Starting to run ${step}\n"

. /etc/sysconfig/heat-params

vault_ssh_enabled=$(echo $VAULT_SSH_ENABLED | tr '[:upper:]' '[:lower:]')
vault_url=$(echo $VAULT_URL | tr '[:upper:]' '[:lower:]')


if [[ "${vault_ssh_enabled}" = "true" && -n "${vault_url}" ]]; then


# Just used to get a guaranteed empty Docker context dir
empty_dir="$(mktemp -d)"

dockerfile="$(mktemp)"

cleanup() {
  if [ -d "$empty_dir" ]
  then
    rm -rf "$empty_dir"
  fi
  if [ -f "$dockerfile" ]
  then
    rm -f "$dockerfile"
  fi
}
trap cleanup EXIT

echo j/98+QEAAAABAAAAEAAAAI3/fPkPAAAAU0UgTGludXggTW9kdWxlAgAAABMAAAABAAAACAAAAAAAAAAJAAAAdmF1bHQtb3RwAwAAADEuMEAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAIAAAAKAAAAAAAAAAIAAAABAAAAAQAAAAAAAAB0Y3Bfc29ja2V0DAAAAAEAAABuYW1lX2Nvbm5lY3QEAAAAAAAAAAEAAAACAAAAAgAAAAAAAABmaWxlBgAAAAIAAABjcmVhdGUEAAAAAQAAAG9wZW4BAAAAAQAAAAgAAAABAAAAAAAAAG9iamVjdF9yQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAADAAAAAwAAAAsAAAADAAAAAQAAAAEAAAAAAAAAQAAAAAAAAAAAAAAAaHR0cF9wb3J0X3QJAAAAAQAAAAEAAAABAAAAAAAAAEAAAAAAAAAAAAAAAHZhcl9sb2dfdAYAAAACAAAAAQAAAAEAAAAAAAAAQAAAAAAAAAAAAAAAc3NoZF90AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAEAAAAAAAAAAAAAAAMAAAABAAAAAAAAAEAAAABAAAAAAQAAAAAAAAACAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAAEAAAAAAAAAAQAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAABAAAAAQAAAAAAAABAAAAAQAAAAAEAAAAAAAAAAgAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAABAAAAAAAAAAEAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAgAAAAEAAAAAAAAAQAAAAEAAAAABAAAAAAAAAAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAAQAAAAAAAAAEAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAABAAAAAgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAEAAAAABAAAAAAAAAAMAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAEAAAAABAAAAAAAAAAcAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAgAAAEAAAABAAAAAAQAAAAAAAAADAAAAAAAAAEAAAABAAAAAAQAAAAAAAAABAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAKAAAAdGNwX3NvY2tldAEAAAABAAAAAQAAAAQAAABmaWxlAQAAAAEAAAABAAAAAQAAAAgAAABvYmplY3RfcgIAAAABAAAAAQAAAAMAAAALAAAAaHR0cF9wb3J0X3QBAAAAAQAAAAEAAAAJAAAAdmFyX2xvZ190AQAAAAEAAAABAAAABgAAAHNzaGRfdAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | base64 -d > $empty_dir/vault-otp.pp


# NOTE - not sure if policycoreutils-devel is necessary here, didn't test it with it removed
cat >"$dockerfile" <<DEOF
FROM fedora
RUN yum install -y policycoreutils-python-utils policycoreutils-devel && yum clean all
COPY vault-otp.pp /root/vault-otp.pp
DEOF

image_name="$(podman build -f "$dockerfile" "$empty_dir" | tail -n1)"

secontainer() {
  podman run --privileged --rm \
    -v /var/run:/var/run \
    -v /etc/selinux:/etc/selinux \
    -v /proc:/proc \
    -v /sys:/sys \
    "$image_name" "$@"
}

secontainer semodule -i /root/vault-otp.pp

# workaround from https://github.com/coreos/fedora-coreos-tracker/issues/701 to keep selinux policy files in base config state
rsync -rcl /usr/etc/selinux/ /etc/selinux/

fi